### ISSUE TITLE
Overview of Programme CSS

### ISSUE THREAD

**Issue by MinaAlmasi** [cohure/CHR2024-website#98]
# Programme Styling
The Programme CSS became quite a beast as we came closer to CHR2024. In case you want to use it again, I have provided an overview here. 

Most of what needs to be changed is the manual colouring, I have marked everything that needs some modification with 🔴. 

TOC:
- 1 TABS
    - 1.1 See CSS code
    - 1.2 Taken from Codepen (🔴)
    - 1.3 Manual colour of tabs (🔴)
    - 1.4 Javascript to make the tabs more useful/dynamic
    - 1.5 HTML for tabs
- 2 DETAILED VIEW
    - 2.1 See CSS code
    - 2.2 Manual choice of colours (🔴)
- 3 Table
    - 3.1 See CSS code
- 4 Zoom buttons
    - 4.1 See CSS code
    - 4.2 Manual colours of borders and buttons (🔴)

## 1 TABS 
The first thing you encounter in the css is the tab-styling, where you can switch between days. There is really nothing to change here except for maybe the color of the links (see section below).

<img width="849" alt="Screenshot 2025-01-16 at 12 46 19" src="https://github.com/user-attachments/assets/e048903c-cede-4baf-9552-d160233cd33c" />

### 1.1 See CSS code
<details>
  <summary>Click to expand CSS CODE</summary>

  ```css
  /* CSS TABS */
/* modified from https://codepen.io/markcaron/pen/MvGRYV */
/* - NOTE THAT THEY REQUIRE A LITTLE JAVA TO FUNCTION PROPERLY, which is written at the END of programme.md*/

/* interaction part of CSS */
.tabset > input[type="radio"] {
  position: absolute;
  left: -200vw;
}

.tabset .tab-panel {
  display: none;
}

.tabset > input:first-child:checked ~ .tab-panels > .tab-panel:first-child,
.tabset > input:nth-child(3):checked ~ .tab-panels > .tab-panel:nth-child(2),
.tabset > input:nth-child(5):checked ~ .tab-panels > .tab-panel:nth-child(3),
.tabset > input:nth-child(7):checked ~ .tab-panels > .tab-panel:nth-child(4),
.tabset > input:nth-child(9):checked ~ .tab-panels > .tab-panel:nth-child(5),
.tabset > input:nth-child(11):checked ~ .tab-panels > .tab-panel:nth-child(6) {
  display: block;
}

/* Styling*/
.tabset > label { /* label */
  position: relative;
  display: inline-block;
  padding: 15px 15px 25px;
  border: 1px solid transparent;
  border-bottom: 0;
  cursor: pointer;
  font-weight: 600;
  font-size: 1.2em !important;
}

.tabset > label::after {
  content: "";
  position: absolute;
  left: 15px;
  bottom: 10px;
  width: 22px;
  height: 4px;
  background: #8d8d8d; /* inactive tab: color of line underneath tab*/
}

input:focus-visible + label {
  outline: 2px solid rgba(0,102,204,1);
  border-radius: 3px;
}

.tabset > label:hover,
.tabset > input:focus + label,
.tabset > input:checked + label {
  color: #0B25DA; /* active tab: color of label*/
}

.tabset > label:hover::after,
.tabset > input:focus + label::after,
.tabset > input:checked + label::after {
  background: #0B25DA; /* active tab: color of line underneath tab */
}

.tabset > input:checked + label {
  border-color: #ccc;
  border-bottom: 1px solid #fff;
  margin-bottom: -1px;
}

.tab-panel {
  padding: 30px 0;
  border-top: 1px solid #ccc;
}
```
</details>

### 1.2 Taken from codepen (🔴)
The CSS code is taken from codepen with a very open license with permission to use and modify, sell etc. It is modified slightly (e.g., tab colors - see next section). Might be worth to re-check the license in 2025 to ensure it has not changed:

https://codepen.io/h14turkiye/details/gOyNEev

### 1.3 Manual color of tabs  (🔴)
The colour for the tabs is (#0B25DA) i.e., $\color{#0B25DA}\text{Wednesday}$ that is manually written in the css `color: #0B25DA; /* active tab: color of label*/` 

This might need to change if you have a diff. color scheme for links next year. 

### 1.4 Javascript to make the tabs more useful/dynamic
I needed to write some javascript custom to the tabs for two purposes:
1. Ability to link to a "day" and that day would be activated - e.g., https://2024.computational-humanities-research.org/programme/#thursday
2. Ability to link to a section within a day, and having that day activated to direct directly to the section e.g., https://2024.computational-humanities-research.org/programme/#session8

I got some help from ChatGPT (as I don't normally write JS) but it works quite flawlessly. Note that this is placed at the very bottom of the `programme.md` after all written content. As far as I know, this is best practice.

<details>
  <summary>JAVA CODE</summary>

```js
<!-- JS for making tabs and sections inside tabs linkable -->
<script>
function activateTabFromHash() {
    // get the current hash from the URL
    var hash = window.location.hash;
    if (hash) {
        // remove the '#' character
        var id = hash.substring(1);

        // first, try to find a radio button (tab control) with that ID
        var tabRadio = document.getElementById(id);
        if (tabRadio && tabRadio.name === 'tabset') {
            // activate the corresponding tab
            tabRadio.checked = tru
        } else {
            // if not found, try to find an element within a tab panel
            var targetElement = document.getElementById(id);
            if (targetElement) {
                // find the closest ancestor with class 'tab-panel'
                var tabPanel = targetElement.closest('.tab-panel');
                if (tabPanel) {
                    // get the id of the tab panel
                    var panelId = tabPanel.id;
                    // find the radio button whose aria-controls matches the panel id
                    var tabRadio = document.querySelector('input[name="tabset"][aria-controls="' + panelId + '"]');
                    if (tabRadio) {
                        // activate the corresponding tab
                        tabRadio.checked = true;
                    }
                }
            }
        }
    }
}

document.addEventListener("DOMContentLoaded", function() {
    activateTabFromHash();

    // update the URL hash when a new tab is selected
    var radios = document.querySelectorAll('.tabset > input[type="radio"]');
    radios.forEach(function(radio) {
        radio.addEventListener('change', function() {
            if (this.checked) {
                // update the URL hash to the radio button's ID
                history.replaceState(null, null, '#' + this.id);
            }
        });
    });
});

// listen for hash changes (e.g., when clicking on links to anchors)
window.addEventListener('hashchange', function() {
    activateTabFromHash();
});
</script>
```
</details>

### 1.5 HTML for tabs 
All content pertaining to the tabs needs to be written underneath the `<div class='tabset'>` and `<div class="tab-panels">`. For content pertaining to each tab (i.e., each tab), they need to be written underneath a new section with the class `"tab-panel"`

```html
<div class="tabset">

  <!-- button creation -->
  <!-- TUE -->
  <input type="radio" name="tabset" id="tuesday" aria-controls="tuesday">
  <label for="tuesday">Tuesday</label>
  <!-- WED -->
  <input type="radio" name="tabset" id="wednesday" aria-controls="wednesday" checked>
  <label for="wednesday">Wednesday</label>
  <!-- THUR -->
  <input type="radio" name="tabset" id="thursday" aria-controls="thursday">
  <label for="thursday">Thursday</label>
  <!-- FRI -->
  <input type="radio" name="tabset" id="friday" aria-controls="friday">
  <label for="friday">Friday</label>
  
  <!-- content -->
  <div class="tab-panels">
  <section id="tuesday" class="tab-panel" alt="tab showing the schedule for tuesday">
```
Note that the first part pertains to creating the tab buttons that need ids to be referred to. 

The `checked` written after Wednesday ensure that the active tab starts on Wednesday. I moved this `checked` each day during the conference to make the page start on the current day of the conference. 

## 2 DETAILED VIEW 
Here we are talking about: 
<img width="764" alt="Screenshot 2025-01-16 at 12 48 11" src="https://github.com/user-attachments/assets/4a7654b9-c23e-4480-a014-9a77218fe674" />

### 2.1 See CSS code
<details>
  <summary>Click to expand CSS CODE</summary>

 ```css
/* PROGRAMME STYLING in 'DETAILED VIEW' */
    .paper-entry {
        font-size: 1.15em;
        margin: 0;
        padding: 1rem 1.5rem;
        border-left: 1px solid rgba(0,0,0,0.1);
        border-right: 1px solid rgba(0,0,0,0.1);
    }
    .paper-entry:last-child {
        border-bottom: 1px solid rgba(0,0,0,0.1);
        border-radius: 0 0 8px 8px;
    }
    .paper-title {
        font-weight: 500;
    }

    .paper-authors {
        margin-left: 0;
        margin-top: 0em;
        display: block;
        font-style: italic;
        font-size: 0.9em;
    }
    .paper-type {
        font-size: 0.9em;
        vertical-align: super;
        margin-left: 0.25em;
    }
    .session-block {
        margin-bottom: 1.5rem;
        background: #fff;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }
    .session-a h3 {
        background-color: #601843;
        font-weight: 600;
        margin: 0;
        padding: 1rem 1.5rem;
        color: #fff;
        border-radius: 8px 8px 0 0;
        font-size: 1.25rem;
        line-height: 1.4;
    }
    .session-b h3 {
        background-color: #132344;
        font-weight: 600;
        margin: 0;
        padding: 1rem 1.5rem;
        color: #fff;
        border-radius: 8px 8px 0 0;
        font-size: 1.25rem;
        line-height: 1.4;
    }
    .session-a .paper-entry {
        background-color: rgba(96,24,67,0.03);
    }
    .session-b .paper-entry {
        background-color: rgba(19,35,68,0.03);
    }
    .session-a .paper-entry:nth-child(even) {
        background-color: rgba(96,24,67,0.06);
    }
    .session-b .paper-entry:nth-child(even) {
        background-color: rgba(19,35,68,0.06);
    }
    .alt-session h3 {
        background: linear-gradient(45deg, #601843, #132344);
        font-weight: 600;
        margin: 0;
        padding: 1rem 1.5rem;
        color: #fff;
        border-radius: 8px 8px 0 0;
        font-size: 1.25rem;
        line-height: 1.4;
    }
    .alt-session .paper-entry {
        background-color: rgba(19,35,68,0.02);
    }

    .meta-data { /* What is written underneath session A/B title e.g., zoom link, building number, chair */
        display: block;
        font-size: 1em;
        color: #fff;
        text-align: left;
        margin: 0;
        padding: 0rem 1rem 1rem; /* match the h3 padding */
        font-weight: 650;
    }

    /* Session A meta-data style */
    .session-a .meta-data {
        background-color: #601843;
    }

    /* Session B meta-data style */
    .session-b .meta-data {
        background-color: #132344;
    }

    /* Alt session meta-data style */
    .alt-session .meta-data {
        background: linear-gradient(45deg, #601843, #132344);
    }

    .meta-data .separator {
    margin: 0 0.5rem;
    color: rgba(255,255,255,0.8);
    }

    .meta-item {
        display: flex;
        align-items: center;
        gap: 0.5rem;
    }

    /* bordered style */
    .bordered-layout {
        display: flex;
    }

    .meta-section {
        padding: 0 0.5rem;
        border-right: 2px solid rgba(255,255,255,0.7);
    }

    .meta-section:last-child {
        border-right: none;
}

    @media screen and (max-width: 768px) {
        .meta-data {
            font-size: 0.7em !important;
        }
    }
```
</details>

## 2.2 Manual choice of colours (🔴)
Background colours for each heading background and for every paper entry was manually chosen and need to be updated to fit #CHR2025 color scheme: 

```css
    .session-a h3 {
        background-color: #601843;
        font-weight: 600;
        margin: 0;
        padding: 1rem 1.5rem;
        color: #fff;
        border-radius: 8px 8px 0 0;
        font-size: 1.25rem;
        line-height: 1.4;
    }
    .session-b h3 {
        background-color: #132344;
        font-weight: 600;
        margin: 0;
        padding: 1rem 1.5rem;
        color: #fff;
        border-radius: 8px 8px 0 0;
        font-size: 1.25rem;
        line-height: 1.4;
```
Basically a problem everywhere it denotes session-a, session-b and alt-session (for gradient in keynotes, lightning talks etc.).

## 3 Table 
For the table overview of the programme for each day:
<img width="462" alt="Screenshot 2025-01-16 at 13 03 03" src="https://github.com/user-attachments/assets/5420efed-895b-4ecc-9323-24cad1b31a81" />

Nothing needs to be changed here!

### 3.1 See CSS code
<details>
  <summary>Click to expand CSS CODE</summary>

  ```css
.schedule-table {
    width: 100%;
    max-width: 1000px;
    border-collapse: separate;
    border-spacing: 0;
    text-align: left; 
    padding-left: 0;
    margin: 3rem 0;
}

.schedule-table tr {
    border-bottom: 100px solid #eee;
}

.schedule-table td {
    padding: 1rem;
    vertical-align: top;
}

.schedule-table .time {
    position: relative; /* Make this a relative container */
    width: 140px;
    font-family: monospace;
    color: #555;
    white-space: nowrap;
}

.schedule-table tr:first-of-type .time::before {
    content: "Time in CET";
    position: absolute;
    top: -0.4rem; 
    left: 1rem;
    right: 0;
    font-size: 0.8rem;
    color: #999;
    text-align: left;
}

.schedule-table .highlight {
    font-weight: bold;
}

.schedule-table .location {
    font-size: 0.875rem;
    color: #383D43;
}

.schedule-table .location a {
    color: #383D43;
}
```
</details>

## 4 Zoom buttons 
Only thing that needs to change is the colours of the zoom buttons (see 4.2) 

<img width="808" alt="Screenshot 2025-01-16 at 13 08 49" src="https://github.com/user-attachments/assets/9e41a89a-56eb-461a-869b-4ae9cf0c5249" />

### 4.1 See CSS code 
<details>
  <summary>Click to expand CSS CODE</summary>

  ```css
/* ZOOM CARDS - They are supposed to resemble the banners in venue.md, but with a twist to signal that they don't do exactly the same */
.cards-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 1.5rem;
  padding: 1rem 0 0 0;
  max-width: 1200px;
  margin: 0 auto;
}

.card {
  border-radius: 10px;
  transition: all 0.3s ease;
  overflow: hidden;
  background: white;
  border: 2px solid;
}

.session-a { border-color: #601843; }
.session-b { border-color: #132344; }

.card a {
  color: #333;
  text-decoration: none !important;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 15px;
  height: 100%;
}

.text-content {
  flex-grow: 1;
}

.zoom-indicator {
  font-weight: 600;
  font-size: 1.1rem;
  margin-bottom: 0.25rem;
  color: inherit;
}

.card span {
  display: block;
  font-size: 0.9rem;
  color: #666;
  margin-top: 0.25rem;
}

.arrow-circle {
  width: 36px;
  height: 36px;
  border-radius: 50%;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-left: 10px;
  transition: all 0.3s ease;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.session-a .arrow-circle {
  background-color: #601843;
  color: white;
}

.session-b .arrow-circle {
  background-color: #132344;
  color: white;
}

.card:hover {
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
  transform: translateY(-3px);
  border-color: rgba(96, 24, 67, 0.8); /* Slightly intensify the border colour */
}

@media (max-width: 768px) {
  .cards-grid {
    grid-template-columns: 1fr;
    gap: 0rem;
  }
  
  .arrow-circle {
    width: 28px;
    height: 28px;
  }
  
  .zoom-indicator {
    font-size: 1rem;
  }

  .card:hover {
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
    transform: translateY(-1px);
  }
```
</details> 

### 4.2 Manual colors of borders and buttons (🔴)
Change for .session-a and session-b:

```css
.session-a { border-color: #601843; }
.session-b { border-color: #132344; }

.session-a .arrow-circle {
  background-color: #601843;
  color: white;
}

.session-b .arrow-circle {
  background-color: #132344;
  color: white;
}
```
